// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownload(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddDownload'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearMediaList() {
  return window['go']['main']['App']['ClearMediaList']();
}

export function DeleteDownload(arg1, arg2) {
  return window['go']['main']['App']['DeleteDownload'](arg1, arg2);
}

export function DeleteQueue(arg1) {
  return window['go']['main']['App']['DeleteQueue'](arg1);
}

export function FetchVideoMetadata(arg1) {
  return window['go']['main']['App']['FetchVideoMetadata'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownloads() {
  return window['go']['main']['App']['GetDownloads']();
}

export function GetMediaList() {
  return window['go']['main']['App']['GetMediaList']();
}

export function GetQueues() {
  return window['go']['main']['App']['GetQueues']();
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function ProcessQueue(arg1) {
  return window['go']['main']['App']['ProcessQueue'](arg1);
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function RefreshLink(arg1, arg2) {
  return window['go']['main']['App']['RefreshLink'](arg1, arg2);
}

export function RemoveMediaItem(arg1) {
  return window['go']['main']['App']['RemoveMediaItem'](arg1);
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveQueue(arg1) {
  return window['go']['main']['App']['SaveQueue'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetSpeedLimit(arg1) {
  return window['go']['main']['App']['SetSpeedLimit'](arg1);
}

export function StartQueue(arg1) {
  return window['go']['main']['App']['StartQueue'](arg1);
}

export function StopQueue(arg1) {
  return window['go']['main']['App']['StopQueue'](arg1);
}
