// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function AddDownload(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<models.DownloadTask>;

export function CheckDependencies():Promise<Record<string, boolean>>;

export function CheckForUpdates():Promise<models.UpdateInfo>;

export function ClearMediaList():Promise<void>;

export function DeleteDownload(arg1:string,arg2:boolean):Promise<void>;

export function DeleteQueue(arg1:string):Promise<void>;

export function FetchVideoMetadata(arg1:string):Promise<services.VideoMetadata>;

export function GetConfig():Promise<models.AppConfig>;

export function GetDownloads():Promise<Array<models.DownloadTask>>;

export function GetMediaList():Promise<Array<models.MediaItem>>;

export function GetQueues():Promise<Array<models.DownloadQueue>>;

export function IsAutoStartEnabled():Promise<boolean>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function PauseDownload(arg1:string):Promise<void>;

export function ProcessQueue(arg1:string):Promise<void>;

export function ReadClipboard():Promise<string>;

export function RefreshLink(arg1:string,arg2:string):Promise<void>;

export function RemoveMediaItem(arg1:string):Promise<void>;

export function ResumeDownload(arg1:string):Promise<void>;

export function SaveConfig(arg1:models.AppConfig):Promise<void>;

export function SaveQueue(arg1:models.DownloadQueue):Promise<void>;

export function SelectFolder():Promise<string>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetSpeedLimit(arg1:number):Promise<void>;

export function StartQueue(arg1:string):Promise<void>;

export function StopQueue(arg1:string):Promise<void>;
